INSERT INTO tags (tag) VALUES ('action');
INSERT INTO tags (tag) VALUES ('adventure');
INSERT INTO tags (tag) VALUES ('quiz');
INSERT INTO tags (tag) VALUES ('puzzle');
INSERT INTO tags (tag) VALUES ('horror');
INSERT INTO tags (tag) VALUES ('retro');
INSERT INTO tags (tag) VALUES ('fantasy');
INSERT INTO tags (tag) VALUES ('RPG');
INSERT INTO tags (tag) VALUES ('educational');